server:
  port: 8080
spring:
  application:
    name: spring-boot-demo
  datasource:
    url: jdbc:h2:mem:persondb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
  level:
    root: DEBUG


